//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareInvest.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShareInvest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Administrator과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ADMIN {
            get {
                return ResourceManager.GetString("ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Icon bird_alert {
            get {
                object obj = ResourceManager.GetObject("bird_alert", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Icon bird_awake {
            get {
                object obj = ResourceManager.GetObject("bird_awake", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Icon bird_away {
            get {
                object obj = ResourceManager.GetObject("bird_away", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Icon bird_idle {
            get {
                object obj = ResourceManager.GetObject("bird_idle", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Icon bird_invisible {
            get {
                object obj = ResourceManager.GetObject("bird_invisible", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Icon bird_sleep {
            get {
                object obj = ResourceManager.GetObject("bird_sleep", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   dotnet publish -c release -r win-x64 --no-self-contained과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BUILD {
            get {
                return ResourceManager.GetString("BUILD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *.csproj과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSPROJ {
            get {
                return ResourceManager.GetString("CSPROJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Execute과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EXECUTE {
            get {
                return ResourceManager.GetString("EXECUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The existing launcher is running.||Do you want to force the shutdown?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EXIST {
            get {
                return ResourceManager.GetString("EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시스템 종료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EXIT {
            get {
                return ResourceManager.GetString("EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Launcher과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LAUNCHER {
            get {
                return ResourceManager.GetString("LAUNCHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://github.com/share-invest과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PATH {
            get {
                return ResourceManager.GetString("PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   pwsh과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string POWERSHELL {
            get {
                return ResourceManager.GetString("POWERSHELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   publish과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PUBLISH {
            get {
                return ResourceManager.GetString("PUBLISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   route과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ROUTE {
            get {
                return ResourceManager.GetString("ROUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   appsettings.json과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SETTINGS {
            get {
                return ResourceManager.GetString("SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Source과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SOURCES {
            get {
                return ResourceManager.GetString("SOURCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   동학개미운동과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TITLE {
            get {
                return ResourceManager.GetString("TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It can be fatal to data when manually terminated.||Do you really want to end it?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WARNING {
            get {
                return ResourceManager.GetString("WARNING", resourceCulture);
            }
        }
    }
}
