//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareInvest.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShareInvest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Get-Content -Path access.log -Wait과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ACCESS {
            get {
                return ResourceManager.GetString("ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   runas과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ADMIN {
            get {
                return ResourceManager.GetString("ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   동학개미운동과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ANT {
            get {
                return ResourceManager.GetString("ANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Icon BLACK {
            get {
                object obj = ResourceManager.GetObject("BLACK", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   start nginx과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string COMMAND {
            get {
                return ResourceManager.GetString("COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Icon DOWNLOAD {
            get {
                object obj = ResourceManager.GetObject("DOWNLOAD", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Get-Content -Path error.log -Wait과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *.exe과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EXE {
            get {
                return ResourceManager.GetString("EXE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시스템 종료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EXIT {
            get {
                return ResourceManager.GetString("EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Icon IDLE {
            get {
                object obj = ResourceManager.GetObject("IDLE", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   logs과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOG {
            get {
                return ResourceManager.GetString("LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F:\nginx-1.24.0과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NGINX {
            get {
                return ResourceManager.GetString("NGINX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   major problem arises.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NOTICE {
            get {
                return ResourceManager.GetString("NOTICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   pwsh과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string POWERSHELL {
            get {
                return ResourceManager.GetString("POWERSHELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시작프로그램 등록과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string REGISTER {
            get {
                return ResourceManager.GetString("REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SOFTWARE\Microsoft\Windows\CurrentVersion\Run과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RUN {
            get {
                return ResourceManager.GetString("RUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kiwoom.exe과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SECURITIES {
            get {
                return ResourceManager.GetString("SECURITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시작프로그램 해제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UNREGISTER {
            get {
                return ResourceManager.GetString("UNREGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version Upgrade과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UPDATE {
            get {
                return ResourceManager.GetString("UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Icon UPLOAD {
            get {
                object obj = ResourceManager.GetObject("UPLOAD", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   It can be fatal to data when manually terminated.||Do you really want to end it?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WARNING {
            get {
                return ResourceManager.GetString("WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   C:\Program Files (x86)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string X86 {
            get {
                return ResourceManager.GetString("X86", resourceCulture);
            }
        }
    }
}
